version: '3'

services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"    
    volumes:
      - ./PlataformaCartao:/usr/share/nginx/html
    networks:
      - cartao-network
        
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234567890"
      MYSQL_DATABASE: "saudecartao4"
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - cartao-network

  cartao:
    image: cartao:latest
    ports:
      - 8080:8080
    depends_on:
      - "mysql"
    networks:
      - cartao-network

networks: 
  cartao-network:
    driver: bridge
